---
- hosts: personal
  become: true
  tasks:
    - name: install nginx
      apt:
        name: nginx
      when: ansible_distribution in ["Debian","Ubuntu"]
      notify: run nginx
  handlers:
    - name: run nginx
      service:
        name: nginx
        state: started
